### ISSUE TITLE
Difference between git version and void linux package

### ISSUE THREAD

**Issue by tondorw** [gnotclub/xst#76]
This is a question from a rookie. Any help is appreciated.
First I installed `xst` using `xbps-install`, realizing I could only recompile it with build from source. Then I "`make install`"-ed with `git clone`. The latter seems to have the `delkey` and some other patch. The backspace and arrow keys behave differently which was not a surprise as stated in the FAQ. I found that in the "xbps-install" the keys behave the same as in an unpatched `st`. yet the config.h file from github and void repo seems to be the same. What could be the reason of such difference?
(I still incline to build from source but want to figure out how to remove the patch and let the keys behave as unpatched `st`)

Thank you.

**Comment by actionless** [comment]
cc @vifino

**Comment by vifino** [comment]
Hey.
I didn't write the package, but from what I can tell, the only difference is that it uses the last released version (0.7.1), which is outdated by 30 commits.
It's pre-rename too, so it conflicts with the regular `st` package, which kinda sucks.

I'd suggest creating a new release, which would allow bumping the packages. After all, it's been a long time since the last release.

**Comment by neeasade** [comment]
> It's pre-rename too, so it conflicts with the regular st package, which kinda sucks.

Oh snap. Yeah, better to release now. This will break those who upgrade, but is worth it to fix the conflicts w/ ncurses, vanilla st. Will version bump and release later today.
