### ISSUE TITLE
Font rendering: TrueType with block characters

### ISSUE THREAD

**Issue by hatkidchan** [gnotclub/xst#87]
I'm trying to display images by using block characters. However, xst showing me lines between characters on small resolution. I *can* use bitmap fonts (like in XTerm), but that's hurting my eyes a lot. 

![image](https://user-images.githubusercontent.com/35804000/84569058-62a18280-ad8c-11ea-817b-16431b39ba17.png)
*(on left side: XTerm with bitmap fonts, on right side: xst with TrueType font "Fira Code")*

Is it possible to use bitmap fonts for "line-drawing"/box characters and regular TrueType font for everything else? Or somehow fix rendering?
And yes, I've trying to disable antialiasing, that's not helping at all. This happens on higher font sizes, too.

And if fixing that is not possible (maybe this is problem of TrueType in general?), how can I convert fonts to bitmap format and use it in xst?

**Comment by actionless** [comment]
> Or somehow fix rendering

unless you could proof the opposite, i don't see any rendering problem. it might be what the font which you're using doesn't have such character, so it's using from fallback font which different height

in your position i see two ways to move on - 1) adding such character to your font (for example using `fontforge` or 2) instead of using block character, use space character, and manipulate background color instead of foreground (i think it's more optimal way as will work with any font)

**Comment by hatkidchan** [comment]
Yes, looks like its fonts problem. Thanks. I'm adding box characters to font now. 

And I have another question: is it possible somehow specify fallback font?

**Comment by actionless** [comment]
via `fontconfig`'s config
