### ISSUE TITLE
shortcut ^V doesn't work?

### ISSUE THREAD

**Issue by tmpm697** [gnotclub/xst#92]
I want to use `ctrl-v` instead of `ctrl-shift-v` as in default of `config.h`:

```
{ TERMMOD,              XK_V,           clippaste,      {.i =  0} },
{ TERMMOD,              XK_v,           clippaste,      {.i =  0} }, // test
```
after rebuild `xst` and try to paste with `ctrl-v` it shows `^V`, `ctrl-shift-v` works as expected.

Why `ctrl-v` doesn't work but `ctrl-shift-v` does?

`xst-git` from aur archlinux.

**Comment by neeasade** [comment]
Were you making an edit to config.h in your package definition? the location of the default config.h changed in a recent update `./config.h`/`./config.def.h` instead of `./src/config.h` -- you might need to update your patch location? ctrl-v isn't in the [old config](https://github.com/gnotclub/xst/blob/dda53ae9edaecb09a929388917ea7cdfcaa38fa6/src/config.h) and won't be in the new one -- I'm working on a way to bind keys from xresources soon though, so that might also be a way to get `ctrl-v` binding

**Comment by tmpm697** [comment]
I use xst-git from aur so I edit src/xst/config.h (a copy from config.def.h)

**Comment by neeasade** [comment]
right -- you'll have to update where you edit your config.h because now it's at the top level (no more src folder)

**Comment by tmpm697** [comment]
so where to `update where you edit your config.h` after I edit `xst-git/src/xst/config.h`?

**Comment by tmpm697** [comment]
I change `{ XK_ANY_MOD,           Button3, selpaste,       {.i = 0},      1 },` (Button2 to Button3) in `xst-git/src/xst/config.h` and it worked.

**Comment by avih** [comment]
Unless you modified it, your `config.h` has `#define TERMMOD (ControlMask|ShiftMask)`, so if you want control instead of control=shift, you need to change
```
{ TERMMOD,              XK_V,           clippaste,      {.i =  0} },
```
to
```
{ ControlMask,              XK_V,           clippaste,      {.i =  0} },
```

**Comment by tmpm697** [comment]
@avih right, have `ControlMask` work, I forgot it, thanks.
